### ISSUE TITLE
Emacs lock files confuse punchlist

### ISSUE THREAD

**Issue by vinceatbluelabs** [apiology/punchlist#2]
```
/usr/local/bundle/gems/punchlist-1.2.0/lib/punchlist.rb:61:in `initialize': No such file or directory @ rb_sysopen - .#README.md (Errno::ENOENT)
        from /usr/local/bundle/gems/punchlist-1.2.0/lib/punchlist.rb:61:in `open'
        from /usr/local/bundle/gems/punchlist-1.2.0/lib/punchlist.rb:61:in `look_for_punchlist_items'
        from /usr/local/bundle/gems/punchlist-1.2.0/lib/punchlist.rb:32:in `block in analyze_files'
        from /usr/local/bundle/gems/punchlist-1.2.0/lib/punchlist.rb:31:in `each'
        from /usr/local/bundle/gems/punchlist-1.2.0/lib/punchlist.rb:31:in `analyze_files'
        from /usr/local/bundle/gems/punchlist-1.2.0/lib/punchlist.rb:24:in `run'
        from /usr/local/bundle/gems/punchlist-1.2.0/bin/punchlist:5:in `<top (required)>'
        from /usr/local/bundle/bin/punchlist:16:in `load'
        from /usr/local/bundle/bin/punchlist:16:in `<main>'
rake aborted!
Error detected running punchlist --glob '{Rakefile,Dockerfile,{*,.*}.{md,rb,rake,gemspec,swift,cpp,c,java,py,clj,cljs,scala,js,yml,sh,json},{src,app,config,db,lib,test,spec,feature}/**/{*,.*}.{md,rb,rake,gemspec,swift,cpp,c,java,py,clj,cljs,scala,js,yml,sh,json}}' --excl\
ude-glob '{db/schema.rb}'.  Exit status is 1
```

**Comment by apiology** [comment]
Fixed upstream
